### ISSUE TITLE
Error starting version 1.3.2

### ISSUE THREAD

**Issue by superelmi** [MiSchroe/ioBroker.klf200#250]
klf200.0 | 2024-10-15 15:24:23.422 | debug | Error:  Invalid frame structure.    at  /opt/iobroker/node_modules/klf-200-api/dist/cjs/connection.js:176:36     at TypedEvent.emit  (/opt/iobroker/node_modules/klf-200-api/dist/cjs/utils/TypedEvent.js:72:35)     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)    at async  KLF200SocketProtocol.send  (/opt/iobroker/node_modules/klf-200-api/dist/cjs/KLF200-API/KLF200SocketProtocol.js:100:13)     at async KLF200SocketProtocol.processData  (/opt/iobroker/node_modules/klf-200-api/dist/cjs/KLF200-API/KLF200SocketProtocol.js:56:17)     at async KLF200SocketProtocol.processData  (/opt/iobroker/node_modules/klf-200-api/dist/cjs/KLF200-API/KLF200SocketProtocol.js:41:21)
-- | -- | -- | --
klf200.0 | 2024-10-15 15:24:23.422 | error | Error: Invalid frame structure.
klf200.0 | 2024-10-15 15:24:23.422 | error | Error during initialization of the adapter.

Version 1.3.1 does start.

**Comment by MiSchroe** [comment]
@superelmi Can you please set the protocol level of the adapter to "silly" ("Alle" in German), restart the adapter and post the complete log? Thanks. _Please post the log either as file attachment or as code block, otherwise it's hard to read._

What kind of products do you have connected to the KLF-200? (I have only windows and roller shutters that I can test.)

_You can change the log level e.g. from the settings dialog of the adapter in the top row. Just click on the pencil icon._
![image](https://github.com/user-attachments/assets/872895f9-4986-4f70-a2e6-9675b2c8a7de)

**Comment by superelmi** [comment]
Hello,
find attached the requested log file. I have four VELUX roller shutter connected to the KLF200 only, if that helps.
BR
[KLF200.log](https://github.com/user-attachments/files/17587050/KLF200.log)

**Comment by MiSchroe** [comment]
@superelmi Please check again with version 1.3.3 of the adapter. It should be available in the next 1-2 days on the beta channel of ioBroker or install it from npm.

**Comment by superelmi** [comment]
"Adapter is ready to use"
Version 1.3.3 works as expected so far. Thank you!
